"""Added placeholder localization, org_type.

Revision ID: 081d0483ec25
Revises: 205e03dc1713
Create Date: 2026-07-17 18:47:57.923621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '081d0483ec25'
down_revision: Union[str, Sequence[str], None] = '205e03dc1713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placeholder_registry_localizations',
    sa.Column('placeholder_key', sa.String(length=90), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['placeholder_key'], ['placeholder_registry.key'], ),
    sa.PrimaryKeyConstraint('placeholder_key', 'language_code')
    )
    with op.batch_alter_table('organization_localizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_type', sa.String(length=255), nullable=False))

    with op.batch_alter_table('placeholder_registry', schema=None) as batch_op:
        batch_op.drop_column('label')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placeholder_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('label', sa.VARCHAR(length=30), nullable=True))

    with op.batch_alter_table('organization_localizations', schema=None) as batch_op:
        batch_op.drop_column('org_type')

    op.drop_table('placeholder_registry_localizations')
    # ### end Alembic commands ###
