"""template config + currency format fields

Revision ID: 1ab7787cc917
Revises: c17612701fde
Create Date: 2026-07-04 20:46:47.436758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab7787cc917'
down_revision: Union[str, Sequence[str], None] = 'c17612701fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decimal_places', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('decimal_separator', sa.String(length=1), nullable=False))
        batch_op.add_column(sa.Column('grouping_separator', sa.String(length=1), nullable=False))
        batch_op.add_column(sa.Column('symbol_position', sa.Enum('PREFIX', 'SUFFIX', name='moneysymbolposition'), nullable=False))
        batch_op.add_column(sa.Column('symbol_spacing', sa.Boolean(), nullable=False))
        batch_op.drop_column('symbol')

    with op.batch_alter_table('currency_localizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.String(length=8), nullable=True))

    with op.batch_alter_table('default_template_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('append_currency', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('default_template_config', schema=None) as batch_op:
        batch_op.drop_column('append_currency')

    with op.batch_alter_table('currency_localizations', schema=None) as batch_op:
        batch_op.drop_column('symbol')

    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.VARCHAR(length=2), nullable=False))
        batch_op.drop_column('symbol_spacing')
        batch_op.drop_column('symbol_position')
        batch_op.drop_column('grouping_separator')
        batch_op.drop_column('decimal_separator')
        batch_op.drop_column('decimal_places')

    # ### end Alembic commands ###
