"""Added padding to document sequence table and code_alpha_2 for language table.

Revision ID: 205e03dc1713
Revises: 1ab7787cc917
Create Date: 2026-07-17 14:34:40.876761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205e03dc1713'
down_revision: Union[str, Sequence[str], None] = '1ab7787cc917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_sequences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('padding', sa.Integer(), nullable=False))

    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_alpha_2', sa.String(length=2), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_column('code_alpha_2')

    with op.batch_alter_table('document_sequences', schema=None) as batch_op:
        batch_op.drop_column('padding')

    # ### end Alembic commands ###
