"""assets, template persistence.

Revision ID: a753d12cd791
Revises: 081d0483ec25
Create Date: 2026-07-21 21:00:14.350225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a753d12cd791'
down_revision: Union[str, Sequence[str], None] = '081d0483ec25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('sha256')
    )
    op.create_table('template_assets',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('asset_sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['asset_sha256'], ['assets.sha256'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('template_id', 'asset_sha256')
    )
    with op.batch_alter_table('document_type_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    with op.batch_alter_table('measurement_unit_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    with op.batch_alter_table('placeholder_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('tax_id_system_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('type')
        batch_op.drop_column('name')

    with op.batch_alter_table('tax_id_system_registry', schema=None) as batch_op:
        batch_op.drop_column('active')
        batch_op.drop_column('system')

    with op.batch_alter_table('placeholder_registry', schema=None) as batch_op:
        batch_op.drop_column('system')

    with op.batch_alter_table('measurement_unit_registry', schema=None) as batch_op:
        batch_op.drop_column('active')
        batch_op.drop_column('system')

    with op.batch_alter_table('document_type_registry', schema=None) as batch_op:
        batch_op.drop_column('active')
        batch_op.drop_column('system')

    op.drop_table('template_assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
