"""initial schema

Revision ID: c17612701fde
Revises: 
Create Date: 2026-07-02 20:55:19.316493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c17612701fde'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('symbol', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('document_type_registry',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('languages',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('label_en', sa.String(length=25), nullable=False),
    sa.Column('label_uk', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('measurement_unit_registry',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('placeholder_registry',
    sa.Column('key', sa.String(length=90), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('type', sa.Enum('SCALAR', 'TABLE', 'COLUMN', name='placeholdertype'), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('representatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snap_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=18), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snap_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_id_system_registry',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('placeholders', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('swift', sa.String(length=11), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iban')
    )
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.create_index('idx_organization_id', ['organization_id'], unique=False)

    op.create_table('country_localizations',
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('country_code', 'language_code')
    )
    op.create_table('currency_localizations',
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=90), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('currency_code', 'language_code')
    )
    op.create_table('default_template_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_language_code', sa.String(length=3), nullable=False),
    sa.Column('secondary_language_code', sa.String(length=3), nullable=True),
    sa.Column('document_type_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['document_type_code'], ['document_type_registry.code'], ),
    sa.ForeignKeyConstraint(['primary_language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['secondary_language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type_code', sa.String(length=30), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=32), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_type_code'], ['document_type_registry.code'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'document_type_code', 'prefix', name='unique_organization_id_document_type_prefix')
    )
    op.create_table('document_type_registry_localizations',
    sa.Column('document_type_code', sa.String(length=30), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['document_type_code'], ['document_type_registry.code'], ),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('document_type_code', 'language_code')
    )
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('measurement_unit_code', sa.String(length=30), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['measurement_unit_code'], ['measurement_unit_registry.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurement_unit_registry_localizations',
    sa.Column('measurement_unit_code', sa.String(length=30), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['measurement_unit_code'], ['measurement_unit_registry.code'], ),
    sa.PrimaryKeyConstraint('measurement_unit_code', 'language_code')
    )
    op.create_table('organization_localizations',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'language_code')
    )
    op.create_table('organization_representative_association',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('representative_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'representative_id')
    )
    op.create_table('representative_localizations',
    sa.Column('representative_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], ),
    sa.PrimaryKeyConstraint('representative_id', 'language_code')
    )
    op.create_table('snap_bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('swift', sa.String(length=11), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['snap_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snap_organization_localizations',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['snap_organizations.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'language_code')
    )
    op.create_table('snap_representatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['snap_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=25), nullable=False),
    sa.Column('document_type_code', sa.String(length=30), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('primary_language_code', sa.String(length=3), nullable=False),
    sa.Column('secondary_language_code', sa.String(length=3), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['snap_organizations.id'], ),
    sa.ForeignKeyConstraint(['contractor_id'], ['snap_organizations.id'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['document_type_code'], ['document_type_registry.code'], ),
    sa.ForeignKeyConstraint(['primary_language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['secondary_language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['template_id'], ['snap_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_issue_date_serial_document_type', ['issue_date', 'serial', 'document_type_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_issue_date'), ['issue_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_serial'), ['serial'], unique=True)

    op.create_table('tax_id_system_registry_localizations',
    sa.Column('tax_id_system_code', sa.String(length=30), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['tax_id_system_code'], ['tax_id_system_registry.code'], ),
    sa.PrimaryKeyConstraint('tax_id_system_code', 'language_code')
    )
    op.create_table('tax_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('tax_id_system_code', sa.String(length=30), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('value', sa.String(length=17), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tax_id_system_code'], ['tax_id_system_registry.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'country_code', 'tax_id_system_code', name='unique_organization_tax_id_system')
    )
    with op.batch_alter_table('tax_ids', schema=None) as batch_op:
        batch_op.create_index('idx_country_system_value', ['country_code', 'tax_id_system_code', 'value'], unique=False)

    op.create_table('bank_account_localizations',
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_info', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('bank_account_id', 'language_code')
    )
    op.create_table('invoice_line_localizations',
    sa.Column('invoice_line_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['invoice_lines.id'], ),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('invoice_line_id', 'language_code')
    )
    op.create_table('snap_bank_account_localizations',
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('bank_name', sa.String(length=120), nullable=False),
    sa.Column('bank_info', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['snap_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('bank_account_id', 'language_code')
    )
    op.create_table('snap_invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('measurement_unit_code', sa.String(length=30), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['measurement_unit_code'], ['measurement_unit_registry.code'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snap_representative_localizations',
    sa.Column('representative_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['representative_id'], ['snap_representatives.id'], ),
    sa.PrimaryKeyConstraint('representative_id', 'language_code')
    )
    op.create_table('snap_invoice_line_localizations',
    sa.Column('invoice_line_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['snap_invoice_lines.id'], ),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('invoice_line_id', 'language_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snap_invoice_line_localizations')
    op.drop_table('snap_representative_localizations')
    op.drop_table('snap_invoice_lines')
    op.drop_table('snap_bank_account_localizations')
    op.drop_table('invoice_line_localizations')
    op.drop_table('bank_account_localizations')
    with op.batch_alter_table('tax_ids', schema=None) as batch_op:
        batch_op.drop_index('idx_country_system_value')

    op.drop_table('tax_ids')
    op.drop_table('tax_id_system_registry_localizations')
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshots_serial'))
        batch_op.drop_index(batch_op.f('ix_snapshots_issue_date'))
        batch_op.drop_index(batch_op.f('ix_snapshots_created_at'))
        batch_op.drop_index('idx_issue_date_serial_document_type')

    op.drop_table('snapshots')
    op.drop_table('snap_representatives')
    op.drop_table('snap_organization_localizations')
    op.drop_table('snap_bank_accounts')
    op.drop_table('representative_localizations')
    op.drop_table('organization_representative_association')
    op.drop_table('organization_localizations')
    op.drop_table('measurement_unit_registry_localizations')
    op.drop_table('invoice_lines')
    op.drop_table('document_type_registry_localizations')
    op.drop_table('document_sequences')
    op.drop_table('default_template_config')
    op.drop_table('currency_localizations')
    op.drop_table('country_localizations')
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_index('idx_organization_id')

    op.drop_table('bank_accounts')
    op.drop_table('templates')
    op.drop_table('tax_id_system_registry')
    op.drop_table('snap_templates')
    op.drop_table('snap_organizations')
    op.drop_table('representatives')
    op.drop_table('placeholder_registry')
    op.drop_table('organizations')
    op.drop_table('measurement_unit_registry')
    op.drop_table('languages')
    op.drop_table('document_type_registry')
    op.drop_table('currencies')
    op.drop_table('countries')
    # ### end Alembic commands ###
